### PR TITLE
Fix/manifest

### LINKED ISSUE #5: You don't package tests/ subdirectory
also, there are some tests in ``examples/``. Could you clean up, please?

### PR DESCRIPTION
**Pull request by heavenshell**
close #5

### CODE REVIEW

**Comment by mcepl** [comment]
Nope:
```
matej@hubmaier: py-autodoc (pr/6)$ python setup.py sdist
running sdist
running egg_info
writing requirements to autodoc.egg-info/requires.txt
writing autodoc.egg-info/PKG-INFO
writing top-level names to autodoc.egg-info/top_level.txt
writing dependency_links to autodoc.egg-info/dependency_links.txt
reading manifest file 'autodoc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'requirements.txt'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
no previously-included directories found matching '.github'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'examples'
writing manifest file 'autodoc.egg-info/SOURCES.txt'
running check
creating autodoc-0.3
creating autodoc-0.3/autodoc
creating autodoc-0.3/examples
creating autodoc-0.3/autodoc.egg-info
creating autodoc-0.3/docs
creating autodoc-0.3/docs/source
copying files to autodoc-0.3...
copying LICENSE -> autodoc-0.3
copying MANIFEST.in -> autodoc-0.3
copying README.rst -> autodoc-0.3
copying setup.py -> autodoc-0.3
copying ./autodoc/__init__.py -> autodoc-0.3/./autodoc
copying ./autodoc/_compat.py -> autodoc-0.3/./autodoc
copying ./examples/__init__.py -> autodoc-0.3/./examples
copying ./examples/app.py -> autodoc-0.3/./examples
copying ./examples/test_gen_each_case.py -> autodoc-0.3/./examples
copying ./examples/test_pytest.py -> autodoc-0.3/./examples
copying ./examples/test_requests.py -> autodoc-0.3/./examples
copying ./examples/test_unittest.py -> autodoc-0.3/./examples
copying autodoc.egg-info/PKG-INFO -> autodoc-0.3/autodoc.egg-info
copying autodoc.egg-info/SOURCES.txt -> autodoc-0.3/autodoc.egg-info
copying autodoc.egg-info/dependency_links.txt -> autodoc-0.3/autodoc.egg-info
copying autodoc.egg-info/requires.txt -> autodoc-0.3/autodoc.egg-info
copying autodoc.egg-info/top_level.txt -> autodoc-0.3/autodoc.egg-info
copying docs/Makefile -> autodoc-0.3/docs
copying docs/make.bat -> autodoc-0.3/docs
copying docs/source/conf.py -> autodoc-0.3/docs/source
copying docs/source/index.rst -> autodoc-0.3/docs/source
Writing autodoc-0.3/setup.cfg
creating dist
Creating tar archive
removing 'autodoc-0.3' (and everything under it)
matej@hubmaier: py-autodoc (pr/6)$ tar tvf dist/autodoc-0.3.tar.gz 
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/
-rw-r--r-- matej/users    1531 2018-05-21 11:59 autodoc-0.3/LICENSE
-rw-r--r-- matej/users     265 2018-05-21 12:24 autodoc-0.3/MANIFEST.in
-rw-r--r-- matej/users    6256 2018-05-21 12:24 autodoc-0.3/PKG-INFO
-rw-r--r-- matej/users    4130 2018-05-21 11:59 autodoc-0.3/README.rst
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/autodoc/
-rw-r--r-- matej/users    7204 2018-05-21 11:59 autodoc-0.3/autodoc/__init__.py
-rw-r--r-- matej/users    1372 2018-05-21 11:59 autodoc-0.3/autodoc/_compat.py
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/
-rw-r--r-- matej/users    6256 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/PKG-INFO
-rw-r--r-- matej/users     462 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/SOURCES.txt
-rw-r--r-- matej/users       1 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/dependency_links.txt
-rw-r--r-- matej/users      18 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/requires.txt
-rw-r--r-- matej/users      17 2018-05-21 12:24 autodoc-0.3/autodoc.egg-info/top_level.txt
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/docs/
-rw-r--r-- matej/users    6775 2018-05-21 11:59 autodoc-0.3/docs/Makefile
-rw-r--r-- matej/users    6712 2018-05-21 11:59 autodoc-0.3/docs/make.bat
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/docs/source/
-rw-r--r-- matej/users    7934 2018-05-21 11:59 autodoc-0.3/docs/source/conf.py
-rw-r--r-- matej/users    4427 2018-05-21 11:59 autodoc-0.3/docs/source/index.rst
drwxr-xr-x matej/users       0 2018-05-21 12:24 autodoc-0.3/examples/
-rw-r--r-- matej/users       0 2018-05-21 11:59 autodoc-0.3/examples/__init__.py
-rw-r--r-- matej/users    1436 2018-05-21 11:59 autodoc-0.3/examples/app.py
-rw-r--r-- matej/users    1352 2018-05-21 11:59 autodoc-0.3/examples/test_gen_each_case.py
-rw-r--r-- matej/users     911 2018-05-21 11:59 autodoc-0.3/examples/test_pytest.py
-rw-r--r-- matej/users    2596 2018-05-21 11:59 autodoc-0.3/examples/test_requests.py
-rw-r--r-- matej/users    1268 2018-05-21 11:59 autodoc-0.3/examples/test_unittest.py
-rw-r--r-- matej/users      38 2018-05-21 12:24 autodoc-0.3/setup.cfg
-rw-r--r-- matej/users    1445 2018-05-21 11:59 autodoc-0.3/setup.py
matej@hubmaier: py-autodoc (pr/6)$ 
```
I still see the line ``prune tests`` in ``MANIFEST.in``.

**Comment by heavenshell** [comment]
@mcepl Thx. fixed.
Could you review this again?

**Comment by mcepl** [comment]
I probably just don't understand. Could you please show me the output of this sequence of commands?
```bash
$ cd <repository>
$ python setup.py sdist
$ export TARBALL=$(readlink -f dist/*.tar.gz)
$ mkdir /tmp/test_tarball
$ cd /tmp/test_tarball
$ tar xvf $TARBALL
$ cd autodoc-*
$ python setup.py test
```

**Comment by heavenshell** [comment]
I think last `python setup test` fail is a happy path.
I excluded tests at `setup.py`.

**Comment by mcepl** [comment]
> I excluded tests at setup.py.

Which is the problem, AFAIS. I am a packager for OpenSUSE, and we try to run test-suites on all (or most) packages possible. I am sure other distros would love to do the same. Don't you want your users be able to test the package before actually committing to it?

**Comment by heavenshell** [comment]
Generally Python library author does not includes `tests` to PyPi.
https://github.com/search?l=Python&q=find_packages%28exclude%3D&type=Issues

If you upload `tests` to PyPi, you can do like this.

```
import autodoc
import tests.apps
```

`tests` installed to top level and `tests` namespace is too generic.

**Comment by heavenshell** [comment]
@mcepl 0.4 Released https://pypi.org/project/autodoc/
Thank you for review and pointing out this.

**Comment by mcepl** [comment]
I am just lost for words. You threw me into the throes of existential crisis. I am not sure now whether there is any hope for meaningful human communication ever. You apparently still did not understand what was my problem even after so many comments.

What including ``tests/`` subdirectory has to do with installing it in ``$PYTHONPATH``? I would think that nothing, so I have happily my package M2Crypto including ``tests/`` in its [tarball](https://files.pythonhosted.org/packages/41/50/7d85dc99b1c4f29eca83873d851ec29a8e484a66b31351e62e30be9db7d1/M2Crypto-0.30.1.tar.gz), while certainly not installing it into ``$PYTHONPATH`` (run ``pip install --user m2crypto``).

**Comment by heavenshell** [comment]
@mcepl Sorry about lost communication(my poor english understand), but honesty I don't understand what is your problem.
Why lot of people say `tests` should exclude to pypi?

**Pull request merged**
